name: dai_codex
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  shared_preferences: ^0.5.4+8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

    # category path
    - assets/json/

    # tarot
    - assets/tarots/characters/
    - assets/tarots/crafting_materials/
    - assets/tarots/creatures/
    - assets/tarots/groups/
    - assets/tarots/history/
    - assets/tarots/letters_and_notes/
    - assets/tarots/magic/
    - assets/tarots/maps/
    - assets/tarots/places/
    - assets/tarots/tales/

    # codex
    - assets/codex/characters/
    - assets/codex/crafting_materials/
    - assets/codex/creatures/
    - assets/codex/groups/
    - assets/codex/history/
    - assets/codex/letters_and_notes/
    - assets/codex/magic/
    - assets/codex/places/
    - assets/codex/tales/

    # map
    - assets/maps/


  fonts:
    - family: Inquisition
      fonts:
        - asset: assets/fonts/Inquisition.ttf
    - family: Estre
      fonts:
        - asset: assets/fonts/estre.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Bold.ttf
        - asset: assets/fonts/Caveat-Regular.ttf
          weight: 700
    - family: Asul
      fonts:
        - asset: assets/fonts/Asul-Regular.ttf
        - asset: assets/fonts/Asul-Bold.ttf
          weight: 700

